"""Replace SailingSession with Race and add racing models

Revision ID: 850f56794e15
Revises: 
Create Date: 2025-02-27 09:40:43.299709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850f56794e15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('boats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('boat_type', sa.String(length=64), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('sail_number', sa.String(length=32), nullable=True),
    sa.Column('hull_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boats_name'), ['name'], unique=False)

    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('boat_id', sa.Integer(), nullable=True),
    sa.Column('race_name', sa.String(length=128), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('max_speed', sa.Float(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('weather_conditions', sa.String(length=256), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gpx_file_path', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_races_boat_id'), ['boat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_races_race_date'), ['race_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_races_user_id'), ['user_id'], unique=False)

    op.create_table('race_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('mark_type', sa.Enum('START', 'FINISH', 'WINDWARD', 'LEEWARD', 'OFFSET', 'OTHER', name='marktype'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('rounding_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('race_marks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_marks_race_id'), ['race_id'], unique=False)

    op.create_table('race_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('segment_type', sa.Enum('UPWIND', 'DOWNWIND', 'REACHING', name='segmenttype'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('max_speed', sa.Float(), nullable=True),
    sa.Column('vmg', sa.Float(), nullable=True),
    sa.Column('start_mark_id', sa.Integer(), nullable=True),
    sa.Column('end_mark_id', sa.Integer(), nullable=True),
    sa.Column('leg_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['end_mark_id'], ['race_marks.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['start_mark_id'], ['race_marks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('race_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_segments_race_id'), ['race_id'], unique=False)

    op.create_table('maneuvers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('maneuver_type', sa.Enum('TACK', 'GYBE', name='maneuvertype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed_before', sa.Float(), nullable=True),
    sa.Column('speed_after', sa.Float(), nullable=True),
    sa.Column('speed_loss', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('heading_before', sa.Float(), nullable=True),
    sa.Column('heading_after', sa.Float(), nullable=True),
    sa.Column('heading_change', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['race_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maneuvers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maneuvers_race_id'), ['race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maneuvers_timestamp'), ['timestamp'], unique=False)

    op.create_table('track_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('vmg', sa.Float(), nullable=True),
    sa.Column('distance_to_next', sa.Float(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['race_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_points_race_id'), ['race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_points_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_points_timestamp'))
        batch_op.drop_index(batch_op.f('ix_track_points_race_id'))

    op.drop_table('track_points')
    with op.batch_alter_table('maneuvers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maneuvers_timestamp'))
        batch_op.drop_index(batch_op.f('ix_maneuvers_race_id'))

    op.drop_table('maneuvers')
    with op.batch_alter_table('race_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_segments_race_id'))

    op.drop_table('race_segments')
    with op.batch_alter_table('race_marks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_marks_race_id'))

    op.drop_table('race_marks')
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_races_user_id'))
        batch_op.drop_index(batch_op.f('ix_races_race_date'))
        batch_op.drop_index(batch_op.f('ix_races_boat_id'))

    op.drop_table('races')
    with op.batch_alter_table('boats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boats_name'))

    op.drop_table('boats')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
